####################################################################################################
#                                                                                                  #
# (c) 2018, 2019 Quantstamp, Inc. This content and its use are governed by the license terms at    #
# <https://s3.amazonaws.com/qsp-protocol-license/V2_LICENSE.txt>                                   #
#                                                                                                  #
####################################################################################################


testnet:
  eth_node:
    provider: !!str "HTTPProvider"
    args:
      endpoint_uri: !!str "https://ropsten.infura.io/v3/${token}"
  audit_contract_abi:
    uri: !!str "./resources/contracts/testnet/QuantstampAudit-v-{major-version}-abi.json"
    metadata: !!str "./resources/contracts/testnet/QuantstampAudit-v-{major-version}-meta.json"
  min_price_in_qsp: !!int 10
  tx_timeout_seconds: !!int 300
  max_assigned_requests: !!int 5
  evt_polling_sec: !!int 5
  block_mined_polling_interval_sec: !!int 5
  block_discard_on_restart: !!int 1
  start_n_blocks_in_the_past: !!int 10
  n_blocks_confirmation: !!int 6
  analyzers:
    - mythril:
        args: !!str "" # No args provided; rely on defaults for now
        storage_dir: !!str "/tmp/mythril"
        timeout_sec: !!int 276
    - securify:
        args: "" # No args provided; rely on defaults for now
        storage_dir: !!str "/tmp/securify"
        timeout_sec: !!int 276
  upload_provider:
      is_enabled: !!bool False
      name: !!str "S3Provider"
      args:
        bucket_name: !!str "qsp-protocol-reports-testnet"
        contract_bucket_name: !!str "qsp-protocol-reports-testnet"
  keystore_file: !!str "./resources/keystore/default.json"
  gas_limit: !!int 1000000
  gas_price:
    # Can be set to either dynamic (compute average gas price of recent blocks) or static (fixed gas price)
    strategy: !!str "dynamic"
    # Only used if strategy is set to "static"
    default_gas_price_wei: !!int 8000000000 # 8 Gwei
    # Sets an upper bound on gas_price which would override high values computed by the strategy.
    # Useful in case the network gets "gas attacked".
    # Only used if strategy is set to "dynamic"
    max_gas_price_wei: !!int 50000000000 # 50 Gwei
  logging:
    streaming:
      is_enabled: !!bool False
  metric_collection:
    is_enabled: !!bool True
    interval_seconds: !!int 30
    destination_endpoint: !!str "https://protocol-staging.quantstamp.com/node-metrics"

mainnet:
  eth_node:
    provider: !!str "HTTPProvider"
    args:
      endpoint_uri: !!str "https://mainnet.infura.io/v3/${token}"
  audit_contract_abi:
    uri: !!str "./resources/contracts/mainnet/QuantstampAudit-v-{major-version}-abi.json" #note that v1 production ABI is not available
    metadata: !!str "./resources/contracts/mainnet/QuantstampAudit-v-{major-version}-meta.json" #note that v1 production ABI is not available
  min_price_in_qsp: !!int 1000
  tx_timeout_seconds: !!int 300
  max_assigned_requests: !!int 5
  evt_polling_sec: !!int 5
  block_mined_polling_interval_sec: !!int 5
  block_discard_on_restart: !!int 1
  n_blocks_confirmation: !!int 6
  analyzers:
    - mythril:
        args: "" # No args provided; rely on defaults for now
        storage_dir: !!str "/tmp/mythril"
        timeout_sec: !!int 276
    - securify:
        args: "" # No args provided; rely on defaults for now
        storage_dir: !!str "/tmp/securify"
        timeout_sec: !!int 276
  upload_provider:
      is_enabled: !!bool False
  keystore_file: !!str "./resources/keystore/default.json"
  gas_limit: !!int 1000000
  gas_price:
    # Can be set to either dynamic (compute average gas price of recent blocks) or static (fixed gas price)
    strategy: !!str "dynamic"
    # Only used if strategy is set to "static"
    default_gas_price_wei: !!int 8000000000 # 8 Gwei
    # Sets an upper bound on gas_price which would override high values computed by the strategy.
    # Useful in case the network gets "gas attacked".
    # Only used if strategy is set to "dynamic"
    max_gas_price_wei: !!int 50000000000 # 50 Gwei
  logging:
    streaming:
      is_enabled: !!bool False
  metric_collection:
    is_enabled: True
    interval_seconds: !!int 30
    destination_endpoint: !!str "https://protocol.quantstamp.com/node-metrics"
